E-14 fix: dashboard link and support link
eduNEXT/edunext-ecommerce pull request #66
Opened 2021-12-21 13:45 UTC by MaferMazu

## Description

This PR was created in order to correct the bug that exists with the redirection of the dashboard and support links.

- [Jira](https://edunext.atlassian.net/browse/PS2021-1334?atlOrigin=eyJpIjoiYjFkNTE0ZjM5ODY2NDYxMWE3M2RmMmUwNWQ5ODE3YzgiLCJwIjoiaiJ9)
- [Documentation](https://docs.google.com/document/d/159hr17KP74jiyiCBmTIObGa46OcwOptqU2oRLU448WY/edit?usp=sharing)
- Juniper PR #61 

## How to test

- Ecommerce

In `<link-ecommerce>/basket `
(example: http://ecommerce.limonero.edunext.link:8130/basket/ in stack-builder local)
![Screenshot from 2021-12-21 09-33-51](https://user-images.githubusercontent.com/35668326/146940093-c931a26d-6bdb-4e10-b078-f6798c7d6244.png)

The first link in info is dashboard link (example http://lms.limonero.edunext.link:8000/ )
And the second is support link (example: http://ecommerce.limonero.edunext.link:8130/basket/ )

2021-12-21 20:37 UTC, MoisesGSalas requested changes
I'm pretty sure you can discard all the changes and only do:

```diff
- Return to your {link_start}{link_middle}{homepage_url}dashboard{link_end}
+ Return to your {link_start}{homepage_url}{link_middle}dashboard{link_end}
```

2021-12-22 21:26 UTC, MaferMazu commented
Thanks for the feedback @MoisesGSalas but both links are inverted and we no longer use things like `as tmsg %}{{ tmsg | force_escape }}`

2021-12-22 22:02 UTC, MoisesGSalas commented
> Thanks for the feedback @MoisesGSalas but both links are inverted and we no longer use things like `as tmsg %}{{ tmsg | force_escape }}`

What do you mean by "both are inverted"? What I'm seeing is that the second link uses `homepage_url` again instead of `support_url`

And about the tmsg filter, the juniper change actually reverts to the [ironwood template](https://github.com/eduNEXT/edunext-ecommerce/blob/open-release/ironwood.master/ecommerce/templates/oscar/basket/basket.html). The filter is being used in lilac.master and idea is to keep the code drift to a minimum.

2021-12-23 16:16 UTC, MaferMazu commented
You are right thanks

2021-12-23 16:27 UTC, MoisesGSalas approved these changes

2021-12-23 17:28 UTC, merged